name: Test Custom Endpoint - PR Review

# This tests the action as a real user would use it
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  test-pr-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare review prompt with smart truncation
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}
          DIFF=$(git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} || echo "No changes found")
          
          # Get diff stats for summary
          DIFF_STATS=$(git diff --stat ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          
          # Calculate diff size and truncate if needed (target max 200KB)
          DIFF_SIZE=${#DIFF}
          MAX_SIZE=200000
          
          if [ $DIFF_SIZE -gt $MAX_SIZE ]; then
            echo "⚠️ Large diff detected ($DIFF_SIZE chars), truncating to first $MAX_SIZE chars"
            DIFF="${DIFF:0:$MAX_SIZE}"
            TRUNCATED=true
          else
            TRUNCATED=false
          fi
          
          cat > /tmp/review-prompt.txt << 'EOF'
          Review this PR for logic errors, security issues, and code quality. Provide specific, actionable feedback with file:line references.

          ## PR Review Summary
          **Intent:** [one-line summary]

          ### Issues to Address
          1. [file:line] - [problem + suggestion]

          ### Suggestions
          - [improvement ideas]

          ### Good Practices
          - [positive notes]

          PR Title: ${{ github.event.pull_request.title }}
          PR Description: ${{ github.event.pull_request.body }}

          Diff Statistics:
          EOF
          echo "$DIFF_STATS" >> /tmp/review-prompt.txt
          echo "" >> /tmp/review-prompt.txt
          
          if [ "$TRUNCATED" = true ]; then
            echo "⚠️ Note: This is a large PR. Diff has been truncated for review. Focus on the changes shown." >> /tmp/review-prompt.txt
            echo "" >> /tmp/review-prompt.txt
          fi
          
          echo "Code Changes:" >> /tmp/review-prompt.txt
          echo "$DIFF" >> /tmp/review-prompt.txt

      - name: Review code with custom AI endpoint
        id: review
        uses: ./
        with:
          api-key: ${{ secrets.CUSTOM_API_KEY }}
          api-base-url: ${{ secrets.CUSTOM_API_BASE_URL }}
          model: ${{ secrets.CUSTOM_MODEL }}
          prompt-file: /tmp/review-prompt.txt

      - name: Post review comment
        if: github.event_name == 'pull_request' && steps.review.outputs.final-message != ''
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '##  AI Code Review\n\n' + process.env.REVIEW
            });
        env:
          REVIEW: ${{ steps.review.outputs.final-message }}

      - name: Show results
        run: |
          echo " Test completed!"
          echo "AI endpoint used: ${{ secrets.CUSTOM_API_BASE_URL }}"
          echo ""
          echo " Review output:"
          echo "${{ steps.review.outputs.final-message }}"